- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Ensure SonarQube Home Directory Exists
  file:
    path: "{{ sonarqube_home }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Run SonarQube Docker Container
  docker_container:
    name: sonarqube
    image: sonarqube
    state: started
    restart_policy: always
    ports:
      - "{{ sonarqube_port }}:{{ sonarqube_port }}"

